version: "3.9"

services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: crud_php
    volumes:
      - .:/var/www/html
    networks:
      - mvc-net

  nginx:
    image: nginx:latest
    container_name: crud_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mvc-net

networks:
  mvc-net:
